#!/bin/bash
# REPLbot demo script to show how to build a simple custom REPL.

echo "Welcome to the demo REPL!"
while true; do
  echo "Available commands:"
  echo "[t] Print date & time"
  echo "[q] Quit"
  read command
  if [ "$command" == "t" ]; then
    echo "The current time is: $(date)"
  elif [ "$command" = "q" ]; then
    echo "Bye!"
    exit
  else
    echo "Unknown command"
  fi
done
