#!/bin/sh
# REPLbot script to run a Java REPL.
#
# Scripts are executed as "./script run <id>" to start the REPL,
# and as "./script kill <id>" to stop it.

DIR="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
case "$1" in
  run)
    echo 'The Java REPL uses commands prefixed with a slash, e.g. /help.'
    echo 'To type these in Slack/Discord, prefix them with space, e.g. " /help".'
    echo
    "$DIR"/helpers/docker-run "$2" openjdk
    ;;
  kill) "$DIR"/helpers/docker-kill "$2" ;;
  *) echo "Syntax: $0 (run|kill) ID"; exit 1 ;;
esac
