#!/bin/sh
# REPLbot script to run a Kotlin REPL.
#
# Scripts are executed as "./script run <id>" to start the REPL,
# and as "./script kill <id>" to stop it.

DIR="$(cd -- "$(dirname "$0")" >/dev/null 2>&1 && pwd -P)"
case "$1" in
  run)
    echo 'The Kotlin REPL uses commands prefixed with a colon, e.g. :help.'
    echo 'To type these in Slack/Discord, add a space after the command'
    echo 'to avoid the emoji auto-complete, e.g. ":help ".'
    echo
    "$DIR"/helpers/docker-run "$2" zenika/kotlin
    ;;
  kill) "$DIR"/helpers/docker-kill "$2" ;;
  *) echo "Syntax: $0 (run|kill) ID"; exit 1 ;;
esac
