#!/bin/sh
# REPLbot script to run a Kotlin REPL.
#
# Scripts are executed as "./script run <id>" to start the REPL,
# and as "./script kill <id>" to stop it.

case "$1" in
  run)
    echo 'The Scala REPL uses commands prefixed with a colon, e.g. :help.'
    echo 'To type these in Slack/Discord, add a space after the command'
    echo 'to avoid the emoji auto-complete, e.g. ":help ".'
    echo
    docker run --rm --name "$2" -it bigtruedata/scala
    ;;
  kill) if [ -n "$(docker ps -q -f "name=$2")" ]; then docker kill "$2"; fi ;;
  *) echo "Syntax: $0 (run|kill) ID"; exit 1 ;;
esac
