#!bash
# REPLbot helper script to run and kill REPLs based on Docker containers
# Example: CONTAINER=openjdk . "$(dirname "$0")"/helpers/docker

COMMAND="$1"
NAME="$2"
[ -n "$CONTAINER" ] || { echo "error: CONTAINER must be set"; exit 1; }
[ -n "$COMMAND" ] || { echo "error: COMMAND must be set"; exit 1; }
[ -n "$NAME" ] || { echo "error: NAME must be set"; exit 1; }

if [ "$COMMAND" = "run" ]; then
  docker run --rm --name "$NAME" -it "$CONTAINER"
elif [ "$COMMAND" = "kill" ]; then
  docker kill "$NAME"
fi
