#!/bin/sh
# REPLbot script to run a Ruby REPL.
#
# Scripts are executed as "./script run <id>" to start the REPL,
# and as "./script kill <id>" to stop it.

CONTAINER=ruby . "$(dirname "$0")"/helpers/docker
