#!/bin/bash

checkDependency() {
    if [ ! -f $1 ]; then
        echo "$1 required"
        exit 1
    fi
}

checkDependency /usr/bin/ssh
checkDependency /usr/bin/tmux
checkDependency /usr/bin/socat

relay_server=localhost
relay_server_port=10022
relay_port=10000
tmux_session=support-10000

tmux has-session -t ${tmux_session} 2>/dev/null
if [ $? != 0 ]; then
    tmux new-session -d -s ${tmux_session}
fi

socat exec:"tmux attach -t ${tmux_session}",pty,raw,echo=0,stderr,setsid,sigint,sane \
    tcp-listen:${relay_port},bind=localhost,reuseaddr &

export SOCAT_PID=$!


echo "Starting new session on ${relay_server} to share port ${relay_port}"
ssh -R ${relay_port}:localhost:${relay_port} -Nf -p ${relay_server_port} ${relay_server}


export SSH_PID=$! SSH_CODE=$?

if [ $SSH_CODE -eq 0 ]; then
    echo "Attach to tmux session ${tmux_session}"
    tmux attach -t ${tmux_session}
else
    echo "SSH session failed"
fi


if [ -z "$3" ]; then tmux kill-session -t ${tmux_session} 2>/dev/null ; fi
kill ${SSH_PID} ${SOCAT_PID}

exit 0
